# 1.异常

dart所有的异常都是unchecked exceptions. 方法不声明可能哪些异常,则不需要去获取任何异常

Exception 和 Error

# 2.抛出异常 throw

```dart
throw FormatException("Expected at lease 1 section");

// 抛出任意对象,但正常抛出Exception或Error实现对象
throw 'Out of llamas!'

void distanceTo(Point other) => throw UnimplementedError();
```

# 3.接收异常
接收异常,就是不让该异常再继续传播了(propagating),`rethrow`特例

1. 一个接收
```dart
try {
    breedMoreLlamas();
} on OutOfLlamasException {
    buyMoreLlamas();
}
```

2. 多个接收,包含非Exception子类

```dart
try {
    breedMoreLlamas();
} on OutOfLlamasException {
    // A specific exption
    buyMoreLlamas();
} on Exception catch (e) {
    // Anything else that is an exception
    print('Unknown excption: $e');
} catch (e) {
    // No specified type, handles all
    print('Something really unknown: $e');
}
```

3. 打印StackTrace catch的第二个参数

```dart
try {
    // ...
} on Exception catch (e) {
    print('Exception details: \n $e');
} catch (e, s) {
    print('Exception details:\n $e');
    print('Stack trace:\n $s');
}
```

4. rethrow关键字

```dart
void misbehave() {
    try {
        dynamic foo = true;
        print(foo ++);  // Runtime error
    } catch (e) {
        print('misbehave() partially handled ${e.runtimeType}.');
        rethrow; // allow callers to see the exception
    }
}

void main() {
    try {
        misbehave();
    } catch (e) {
        print('main() finished handling ${e.runtimeType}.');
    }
}
```

# 4.finally

不管是否发生异常,使用finally都会去运行

```dart
try {
    breedMoreLlamas();
} finally {
    // always clean up, even if an exception is thrown
    cleanLlamaStalls();
}

// 带catch
try {
    breedMoreLlamas();
} catch (e) {
    print('Error : $e');  // handle the exception first
} finally {
    cleanLlamaStalls(); // then clean up.
}
```
